#!/bin/sh
#
# 16 color script.

trap "printf '\033[?25h\033[?7h\n'" EXIT INT

printf '\033[?25l\033[?7l\033[2J\033[H'

for i in 1 2 3 4 5 6; do
    printf '\033[4%sm  \033[m ' "$i"
done

printf '\n'

for i in 1 2 3 4 5 6; do
    printf '\033[10%sm  \033[m ' "$i"
done

read -r _
