#!/bin/sh
#
# 16 color script.

trap "printf '[?25h[?7h\n'" EXIT INT

printf '[?25l[?7l[2J[H'

for i in 1 2 3 4 5 6; do
    printf '[4%sm  [m ' "$i"
done

printf '\n'

for i in 1 2 3 4 5 6; do
    printf '[10%sm  [m ' "$i"
done

read -r _
