#!/usr/bin/env bash
#
# Simple aur helper.
# Use this to install a real aur helper.
#
# Usage: ./aur pkg
shopt -s nullglob nocasematch

AUR_CACHE_DIR="${AUR_CACHE_DIR:-${HOME}/.cache/aur}"
mkdir -p "$AUR_CACHE_DIR"
cd "$AUR_CACHE_DIR" || exit 1

# Download the PKGBUILD / Files.
git clone "https://aur.archlinux.org/${1}.git" 2>/dev/null || \
    { cd "$1" && git pull; }

# Check PKGBUILD / Files.
cd "${AUR_CACHE_DIR}/${1}" || exit
for file in PKGBUILD *.sh *.desktop *.h *.install; do
    read -rn 1 -p "View $file? [y/n] " yn; echo
    [[ "$yn" =~ y ]] && "${EDITOR:-vi}" "$file"
done

# Install package.
makepkg -sfcCi
