#!/usr/bin/env bash
#
# Simple aur helper.
# Use this to install a real aur helper.
#
# Usage: ./saur pkg pkg pkg
SAUR_CACHE_DIR="${HOME}/.cache/saur"
mkdir -p "$SAUR_CACHE_DIR"
cd "$SAUR_CACHE_DIR" || exit 1

# Download the PKGBUILDs.
for pkg in "$@"; do
    cd "$pkg" 2>/dev/null || git clone "https://aur.archlinux.org/${pkg}.git"
done
cd "$SAUR_CACHE_DIR" || exit

# Check PKGBUILDs.
for pkg in "$@"; do
    cd "$pkg" || exit
    read -rn 1 -p "View PKGBUILD for ${pkg}? [y/n] " response; echo
    [[ "${response,,}" =~ y ]] && "${EDITOR:-vi}" PKGBUILD
done
cd "$SAUR_CACHE_DIR" || exit

# Install packages.
for pkg in "$@"; do
    cd "$pkg" || exit
    makepkg -sfci
done
