#!/usr/bin/env bash
# shellcheck disable=SC1090
#
# bar - Dylan Araps
. ~/.cache/wal/colors.sh

vol() {
    cur="$(LC_ALL=C amixer get Master -n |
           awk -F '\\[|\\]' '/[0-9]{1,3}%/ {print $2" "$6}')"

    case "$cur" in
        [0-9]%*|*f*) vol_icon="\\uf026" ;;
        [1-4]?%*)    vol_icon="\\uf027" ;;
        [5-6]?%*|*)  vol_icon="\\uf028" ;;
    esac

    printf "%s %b" "${cur/ *}" "$vol_icon"
}

wif() {
    cur="$(< /tmp/ssid)"
    printf "%s %b" "${cur/connect}" "\\uf1eb"
}

son() {
    cur="$(< /tmp/song)"
    printf "%b  %s" "\\uf001" "$cur"
}

tim() {
    printf "%(%a %d %b  - %l:%M %p)T" "-1"
}

bri() {
    cur="$(< /sys/class/backlight/intel_backlight/brightness)"
    printf "%s %b" "$((cur / 10 + 7))%" "\\uf0eb"
}

bat() {
    cur="$(< /sys/class/power_supply/BAT1/capacity)"
    sta="$(< /sys/class/power_supply/BAT1/status)"

    case "$cur" in
        [0-9])  bat_icon="\\uf244" ;;
        [1-3]?) bat_icon="\\uf243" ;;
        [4-5]?) bat_icon="\\uf242" ;;
        [6-7]?) bat_icon="\\uf241" ;;
        *)      bat_icon="\\uf240" ;;
    esac

    [[ "$sta" == Charging ]] && bat_icon+="  \\uf0e7"

    printf "%s%%  %b" "$cur" "$bat_icon"
}

for((;;)) {
    printf "    %s%s%s    \\n" \
           "$(son)" \
           "%{c}$(tim)" \
           "%{r}$(bri)    $(vol)    $(wif)   $(bat)"
    sleep 2
} |\

lemonbar -db \
         -g 1800x100+700+75 \
         -f "Roboto Mono 22" \
         -f "Font Awesome-15" \
         -n "bar" \
         -B "${1:-#FFFFFF}" \
         -F "${2:-#000000}"
