#!/bin/sh

while :; do
    set -- /sys/class/power_supply/*/capacity

    for bat; do
        read -r cap < "$bat"
        total=$((total + cap))
    done

    printf '%s ' "$((total / $#))%"
    date +'%H:%M'

    total=
    sleep 1
done
