#!/usr/bin/env bash
#
# Control brightness.
#
# Usage: bri [0-100] [+,-], bri [0-100]

bri_path=/sys/class/backlight/intel_backlight
current=$(< "$bri_path/brightness")
max=$(< "$bri_path/max_brightness")

# Set the value based on $2.
((bri=current ${2:-=} $1 * 10))

# Don't allow brightness outside min-max.
((bri > max)) && bri=$max
((bri < 0))   && bri=0

printf %s "$bri" > "$bri_path/brightness"
