#!/usr/bin/env bash
#
# btree - tree in pure bash

cd "$1" &>/dev/null ||:

shopt -s globstar nullglob
printf '%s\n' "${PWD##*/}/"

for item in **; do
    [[ -d $item ]] && dir=/ || dir=

    nest=${item//[^\/]}
    item=${item//[^[:print:]]/^[}

    printf '%s\n' "${nest//\//│  }├─ ${item##*/}${dir}"
done

printf '└%s\b┘\n' "${nest//\//──┴}"
