#!/usr/bin/env bash
#
# bud - a minimal wal replacement

mod() {
    ((r=16#${2:0:2}${3}${4},g=16#${2:2:2}${3}${4},b=16#${2:4:2}${3}${4}))
    ((r=r<0?0:r,g=g<0?0:g,b=b<0?0:b))
    ((r=r>255?255:r,g=g>255?255:g,b=b>255?255:b))
    printf -v "$1" '%02x%02x%02x' "$r" "$g" "$b"
}

img() {
    shopt -s nullglob

    [[ -d $1 ]] && {
        imgs=("${1%/}"/*.{png,jpg,JPG})
        img=${imgs[RANDOM%${#imgs[@]}]}
    }

    printf '%s\n' "${img:-$1}"

    [[ -f ${img:-$1} ]] && {
        img=${img:-$1}
        return
    }

    exit 1
}

col() {
    magic_flags=(
       -alpha off
       -resize 64x64
       -posterize 16
       -fill white
       -colorize 30%
       -modulate '125,175,100'
       -unique-colors
       txt:-
    )

    if [[ -f ${cache_dir}/${img//\//_} ]]; then
        mapfile -t final_pal < "${cache_dir}/${img//\//_}"

    else
        mapfile -ts 1 clrs < <(convert "$img" "${magic_flags[@]}")

        clrs=("${clrs[@]//*\#}")
        clrs=("${clrs[@]// *}")

        mod bg "${clrs[0]}" - 120
        mod fg "${clrs[0]}" + 150
        mod co "$bg" + 125

        final_pal=(
            "$bg"
            "${clrs[@]:10:6}"
            "$fg"
            "$co"
            "${clrs[@]:10:6}"
            "$fg"
        )

        printf '%s\n' "${final_pal[@]}" > "${cache_dir}/${img//\//_}"
    fi

    printf 'c=(%s)\n' "${final_pal[*]}" > "${cache_dir}/colors.sh"
    pal "${final_pal[@]}" &
}

sys() {
    setroot -z "$img" &

    mkdir -p ~/.cache/wal
    echo "$img" > ~/.cache/wal/wal

    sed -i"" \
        -e "s/bg.color: #.*/bg.color: #${final_pal[15]}/" \
        -e "s/text.color: #.*/text.color: #${final_pal[15]}/" \
        -e "s/image.color: #.*/image.color: #${final_pal[15]}/" \
        ~/.themes/thicc/openbox-3/themerc

    openbox --reconfigure
}

main() {
    [[ -d ${cache_dir:=${XDG_CACHE_HOME:=${HOME}/.cache}/buddy} ]] ||
        mkdir -p "$cache_dir"

    img "$1"
    col
    sys &
}

main "$1"
