#!/usr/bin/env bash
#
# bud - a minimal wal replacement

mod() {
    ((r=16#${2:0:2}${3}${4},g=16#${2:2:2}${3}${4},b=16#${2:4:2}${3}${4}))
    ((r=r<0?0:r,g=g<0?0:g,b=b<0?0:b))
    ((r=r>255?255:r,g=g>255?255:g,b=b>255?255:b))
    printf -v "$1" '%02x%02x%02x' "$r" "$g" "$b"
}

img() {
    shopt -s nullglob

    [[ -d $1 ]] && {
        imgs=("${1%/}"/*.{png,jpg,JPG})
        img=${imgs[RANDOM%${#imgs[@]}]}
    }

    [[ -f ${img:-$1} ]] && {
        img=${img:-$1}
        return
    }

    exit 1
}

col() {
    magic_flags=(
       -alpha off
       -resize 25%
       -modulate "${3:-100},${3:-100},100"
       -colors "${1:-16}"
       -unique-colors
       txt:-
    )

    if [[ -f ${cache_dir}/${img//\//_}$light ]]; then
        mapfile -t final_pal < "${cache_dir}/${img//\//_}$light"

    else
        mapfile -ts 1 clrs < <(convert "$img" "${magic_flags[@]}")

        [[ ${#clrs[@]} -lt 16 ]] && {
            col "$((max_colors++))" "$((75+max_colors))" "$((140+max_colors))"
            return
        }

        clrs=("${clrs[@]//*\#}")
        clrs=("${clrs[@]// *}")

        if [[ $light == -l ]]; then
            mod bg "${clrs[0]}" + "${2:-255}"
            mod fg "${clrs[0]}" - 250
            mod co "$bg" - 125
        else
            mod bg "${clrs[0]}" - "${2:-50}"
            mod fg "${clrs[0]}" + 220
            mod co "$bg" + 125
        fi

        final_pal=(
            "$bg"
            "${clrs[@]:9:6}"
            "$fg"
            "$co"
            "${clrs[@]:9:6}"
            "$fg"
        )

        printf '%s\n' "${final_pal[@]}" > "${cache_dir}/${img//\//_}$light"
    fi

    printf 'c=(%s)\n' "${final_pal[*]}" > "${cache_dir}/colors.sh"
    pal "${final_pal[@]}"
}

sys() {
    setroot -z "$img"
}

main() {
    [[ -d ${cache_dir:=${XDG_CACHE_HOME:=${HOME}/.cache}/buddy} ]] ||
        mkdir -p "$cache_dir"

    max_colors=16
    light=$2

    img "$1"
    col
    sys
}

main "$@"
