#!/bin/sh

# Grab the terminal size in cells.
read -r h w <<EOF
$(stty -F /dev/tty size)
EOF

# Clear the screen and move cursor to 0,0.
printf '\033[2J\033[%sH' "$(((h / 4)))"

# Read the input line by line.
while read -r line || [ "$line" ]; do

    # Print each line 1/4 of the terminal width +
    # the length of each line.
    printf '%*s\n' "$(((w / 4) + ${#line}))" "$line"

done < "${1:-/dev/stdin}"

# Move cursor to bottom.
printf '\033[9999B'
