#!/usr/bin/env bash
#
# color1

_() {
    for ((i=1;i<8;i++)) {
        printf '\e[1;3%sm%s ' "$i" "${1:-$i}"
    }
    printf '\e[m'
}

trap printf\ \\\\e[?25h EXIT
printf '\e[2J\e[H'

_ "$1"
echo
_ "$1"

read -p $'\e[?25l' -srn1
