#!/usr/bin/env bash
#
# Print terminal cols with pywal hex colors.

. ~/.cache/wal/colors.sh
printf '\n'

for i in {0..15}; do
    color="color${i}"
    ((i==8)) && printf '\n'
    ((i!=0)) && t=0
    printf '\e[48;5;%s;3%sm %s \e[m' "$i" "${t:-7}" "${!color}"
done
printf '\n\n'
