#!/usr/bin/env bash
#
# Print terminal cols with pywal hex colors.

. ~/.cache/wal/colors.sh

for i in {0..15}; do
    color="color${i}"
    ((i%8==0)) && printf '\n'
    ((i!=0)) && t=0
    printf '%b' "\\e[3${t:-7}m\\e[48;5;${i}m ${!color} \\e[0m"
done
printf '\n\n'
