#!/bin/sh
#
# crupt

old_ifs=$IFS
exec 3<&0

# shellcheck disable=2086
while read -r name dev pass opts err; do
    # Skip comments.
    [ "${name##\#*}" ] || continue

    # Break on invalid crypttab.
    [ "$err" ] && {
        printf 'error: A valid crypttab has a maximum of 4 columns only.\n'
        break
    }

    # Turn 'UUID=*' lines into device names.
    [ "${dev##UUID*}" ] || dev=$(blkid -l -o device -t "$dev")

    # Parse options by turning list into a pseudo array.
    { IFS=,; set -f; set -- $opts; set +f; IFS=$old_ifs; }

    # Create an argument list (no other way to do this in sh).
    for opt; do case $opt in
        discard)            crypt_opts="$crypt_opts --allow-discards" ;;
        readonly|read-only) crypt_opts="$crypt_opts -r" ;;
        tries=*)            crypt_opts="$crypt_opts -T ${opt##*=}" ;;
    esac; done

    # If password is 'none', '-' or empty ask for it.
    case $pass in
        none|-|"") cryptsetup luksOpen $crypt_opts "$dev" "$name" <&3 ;;
        *)         cryptsetup luksOpen $crypt_opts -d "$pass" "$dev" "$name" ;;
    esac

    crypt_opts=
done < /etc/crypttab

exec 3>&-
