#!/usr/bin/env bash
#
# Cycle through an array.
arr=(true false)

cycle() {
    printf '%s ' "${arr[${i:=0}]}"
    ((i=i>=${#arr[@]}-1?0:++i))
}

for _ in {0..100}; do
    cycle
done

while read -r line; do
    printf '%s\n' "$line"
done < ~/.bashrc
