#!/usr/bin/env bash

IFS=:
for ls_color in ${LS_COLORS[@]}; do # For all colors
    color=${ls_color##*=}
    ext=${ls_color%%=*}
    echo -en "\E[${color}m${ext}\E[0m " # echo color and extension
done
echo
