#!/bin/sh

log() {
    printf '\033[32m=>\033[m %s\n' "$@"
}

# Declare variables.
: "${subnet:=}" "${broadcast:=}" "${interface:=}" "${dns:=}"
: "${ip:=}"     "${router:=}"    "${domain:=}"

BROADCAST="broadcast +"

[ "$subnet" ]    && NETMASK="netmask $subnet"
[ "$broadcast" ] && BROADCAST="broadcast $broadcast"

case $1 in
    deconfig)
        log "Setting IP address 0.0.0.0 on $interface"
        ifconfig "$interface" 0.0.0.0
    ;;

    renew|bound)
        log "Setting IP address $ip on $interface"
        ifconfig "$interface" "$ip" "$NETMASK" "$BROADCAST"

        if [ "$router" ] ; then
            log "Deleting routers"
            while route del default gw 0.0.0.0 dev "$interface"; do
                :
            done

            metric=0
            for i in $router; do
                log "Adding router $i"
                route add default gw "$i" dev "$interface" metric "$((metric+=1))"
            done
        fi

        log "Recreating /etc/resolv.conf"
        :> /etc/resolv.conf-$$

        [ "$domain" ] && printf '%s\n' "search $domain" >> "/etc/resolv.conf-$$"

        for i in $dns; do
            log "Adding DNS server $i"
            printf '%s\n' "nameserver $i" >> "/etc/resolv.conf-$$"
        done

        mv -f "/etc/resolv.conf-$$" "/etc/resolv.conf"
    ;;
esac
