#!/usr/bin/env bash
# vim: fdm=marker:noai:ts=4:sw=4
#
# dmen
# Dmenu launch script
#
# Created by Dylan Araps

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

# Get current monitor height
mon_height="$(xrandr --nograb --current | awk -F ' |x|+' '/primary/ {printf $5}')"

# Height
# Bar will be 3% the monitor height
percent=3
height=$((mon_height * percent / 100))

# Run dmenu with variables.
dmenu_run \
    -nb "$color0" -nf "$color7" -sb "$color7" -sf "$color8" \
    -h $height -y $((mon_height - height)) \
    -fn "${bar_font:-"-benis-lemon-medium-r-normal--10-110-75-75-m-50-ISO8859-1"}"


