#!/usr/bin/env bash
# vim: fdm=marker:noai:ts=4:sw=4
#
# dmen
# Dmenu launch script
#
# Created by Dylan Araps
#
# Dependencies: bash, xrandr, awk, dmenu2

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

# Get current monitor height
mon_height="$(xrandr --nograb --current | awk -F ' |x|+' '/primary/ {printf $5}')"

# Height
# Bar will be 3% the monitor height
height=$((mon_height * ${bar_percent:-3} / 100))

# Run dmenu with variables.
dmenu_run \
    -b -nb "$color0" -nf "$color7" -sb "$color7" -sf "$color8" -h $height \
    -fn "${bar_font:-"-benis-lemon-medium-r-normal--10-110-75-75-m-50-ISO8859-1"}"


