#!/usr/bin/env bash
#
# dmenu_custom -

. ~/.cache/buddy/colors.sh

dmenu_run \
    -b \
    -i \
    -p ">" \
    -fn "Roboto:size=16" \
    -nb "#${clrs[0]}" \
    -nf "#${clrs[7]}" \
    -sb "#${clrs[1]}" \
    -sf "#${clrs[0]}"

