#!/bin/sh

efibootmgr -b 0000 -B
efibootmgr -b 0001 -B

efibootmgr --disk /dev/nvme0n1 \
           --part 1 \
           --create KISSLINUXOLD \
           --loader /vmlinuz.old

efibootmgr --disk /dev/nvme0n1 \
           --part 1 \
           --create KISSLINUX \
           --loader /vmlinuz
