#!/usr/bin/env bash
#
# emotes

emotes=(
    '(ง •̀_•́)ง'
    ':^)'
    '( ˘ ³˘)'
    ':>'
    ':|'
    ':)'
    ':3'
    'ᕙ(⇀‸↼‶)ᕗ'
    '( ͡° ᴥ͡°)'
)

main() {
    printf '%s\n' "${emotes[RANDOM%${#emotes[@]}]}"
}

main "$@"
