#!/usr/bin/env bash
# vim: fdm=marker:noai:ts=4:sw=4
#
# Furnace
# For use with coal.
#
# https://github.com/dylanaraps/coal
#
# Created by Dylan Araps

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

# Colorscheme folder
color_dir="$HOME/.colors"

# Create the directory if it doesn't exist.
mkdir -p "$color_dir"


# Export coal colors to files in '$HOME/.colors' {{{


# urxvt
coal --urxvt > "$color_dir/xcolors" && \
    printf "%s\n" "[x] Generated xcolors"

# Shell Envars
coal --shell > "$color_dir/colors.sh" && \
    printf "%s\n" "[x] Generated shell envars"

# GTK2 variables
coal --gtk2 > "$color_dir/colors.rc" && \
    sed -i "4s|include.*|include \"$HOME/.colors/colors.rc\"|" "$HOME/.themes/yellow/gtk-2.0/gtkrc" && \
    printf "%s\n" "[x] Generated GTK2 color variables"

# Firefox css variables
coal --firefox > "$color_dir/colors.css" && \
    sed -i "1s|\@import.*|\@import \"file://$HOME/.colors/colors.css\";|" "$HOME/dotfiles/.config/firefox/userChrome.css" && \
    printf "%s\n" "[x] Generated Firefox color variables"

# SCSS variables
coal --scss > "$color_dir/colors.scss" && \
    sed -i "5s|\@import.*|\@import '$HOME/.colors/colors.scss';|" "$HOME/projects/startpage/scss/style.scss" && \
    sassc --style expanded "$HOME/projects/startpage/scss/style.scss" > "$HOME/projects/startpage/style.css" && \
    printf "%s\n" "[x] Generated SCSS color variables"

# Openbox Theme
ob-theme-gen > "$HOME/.themes/yellow/openbox-3/themerc" && \
    # Send signal to openbox to reload config files
    killall -USR2 openbox && \
    printf "%s\n" "[x] Generated Openbox Theme"


# }}}


