#!/bin/sh

find_pids() {
    for fd in /proc/[1-9]*/fd/*; do
        [ -L "$fd" ] || [ -S "$fd" ] || [ -p "$fd" ] ||
            continue

        pid=${fd%/*/*}

        [ "$(realpath "$fd")" = "$file" ] &&
            pids="$pids ${pid##*/}"
    done

    [ "$pids" ] && printf '%s\n' "${pids# }" || exit 1
}

kill_pids() {
    set -f

    # shellcheck disable=2086
    kill -s "${sig:-KILL}" $pids

    set +f
}

usage() {
    cat <<EOF
Usage: fuser [OPTIONS] FILE or PORT/PROTO

Find processes which use FILEs or PORTs

        -m      Find processes which use same fs as FILEs
        -k      Kill found processes
        -SIGNAL Signal to send (default: KILL)
EOF

exit 1
}

args() {
    [ "$1" ] || usage

    while [ "$1" ]; do
        case $1 in
            -k)      kill=1     ;;
            -m)                 ;;
            -[A-Z]*) sig=${1#-} ;;
            -*)      usage      ;;
            *)       file=$1    ;;
        esac

        shift "$(($# ? 1 : 0))"
    done
}

main() {
    args "$@"
    find_pids

    [ "$kill" ] && kill_pids
}

main "$@"
