#!/usr/bin/env bash

json=$1
json_name=${json##*/}

sed "s/^{/\"${json_name%%.json}\": {/;s/^}/},/" "$json" > "/tmp/$$"

mapfile -t keys < <(jq -r '.address.village.en, .address.island.en, .type.en, .beds, .buildable_size, .price, .size' < "$json")

vals=("addr:${keys[1],,}" "type:${keys[2]}"  "beds:${keys[3]}"
      "bsize:${keys[4]}"  "price:${keys[5]}" "size:${keys[6]}")

addr2="${keys[0],,}, ${keys[1],,}"

while [[ "${start:-0}" -le "${#vals[@]}" ]]; do
    end=$start
    line=

    while [[ "$end" -le "${#vals[@]}" ]]; do
        [[ "${vals[start]}" == addr:* || "${vals[start]}" == type:* ]] && {
            for ((i=start;i<end;i++)) {
                line+="${vals[i]}#"
            }

            resu+=("$line")

            [[ "$line" == *addr:* ]] &&
                resu+=("${line/${vals[0]}/addr:$addr2}")

            line=
        }

        ((end+=1))
    done

    ((start+=1))
done

for res in "${resu[@]}"; do
    grep -qF "\"${json_name%%.json}\"" ".www/db/$res.json" 2>/dev/null &&
        continue

    [ -f ".www/db/$res.json" ] ||
        printf '{\n' > ".www/db/$res.json"

    cat "/tmp/$$" >> ".www/db/$res.json"
done
