#!/bin/sh
#
# git_week

grt >/dev/null
url=$(git remote get-url origin)
grt >/dev/null

git shortlog --since="${1:-8} days ago" --no-merges --format='- %h %s' |

sed -E \
"s@ {6}- (.{7})@    - [\`\1\`]($url/commit/\1)@;s@^(\S)@- **\1@;s@....:\$@**:@"
