#!/usr/bin/env bash

dir=thispersondoesnotexist

mkdir -p "$dir" && cd "$dir" || exit  1

uuid() {
    k=89ab
    for ((i=0;j=RANDOM%256,i<16;++i)) {
        case $i in
            6) printf '4%x'   "$((j%16))" ;;
            8) printf '%c%x'  "${k:RANDOM%${#k}:1}" "$((j%16))" ;;
            3|5|7|9) printf '%02x-' "$j" ;;
            *) printf '%02x'  "$j" ;;
        esac
    }
}

for ((;;)) { wget "https://${dir}.com/image" -O "$(uuid).jpg"; }
