#!/usr/bin/env bash

var=":dylanaraps!~goldi:e@ppp-2-87-108-190.home.otenet.gr PRIVMSG #kisslinux :OK. Writing bi:rch :from scratch.:"
var=":goldie!~goldie@2a02:587:790f:c300:a634:d9ff:fe26:3cc JOIN #rice"

var=${var:1}

: '-->joined'

printf '%10s %s\n' "${_::3}" \
    "${var%%\!*} has ${_:3} #${var##*\#}"
