#!/bin/sh

case $TYPE in
    pre-build)
        IFS=. read -r _start _ < /proc/uptime

        case $PKG in
            llvm|clang|rust)
                export MAKEFLAGS=-j2
            ;;

            tmux)
cat <<EOF > .build
#!/bin/sh -e

export CFLAGS="$CFLAGS -static"

./configure \
    ac_cv_search_forkpty=-lncursesw \
    --prefix=/usr \
    --enable-static

make
make DESTDIR="$1" install
EOF
                chmod +x .build
            ;;
        esac
    ;;

    pre-extract)
        case $PKG in
            firefox|firefox-esr|rust|llvm|clang|gcc)
                mak_dir=$KISS_TMPDIR/build-$pid
                pkg_dir=$KISS_TMPDIR/pkg-$pid
            ;;

            *)
                log "$PKG" "Activating tmpfs"

                mak_dir=/tmp/build-$pid
                pkg_dir=/tmp/pkg-$pid
            ;;
        esac

        mkdir -p "$mak_dir" "$pkg_dir/$PKG/var/db/kiss/installed"
    ;;

    post-build)
        IFS=. read -r _end _ < /proc/uptime

        (
            _s=$((_end - _start))
            _h=$((_s / 60 / 60 % 24))
            _m=$((_s / 60 % 60))

            [ "$_h" = 0 ] || _u="${_u}${_h}h "
            [ "$_m" = 0 ] || _u="${_u}${_m}m "

            log "$PKG" "Build finished in ${_u:-${_s}s}"
        )

        : "${DEST:?DEST is unset}"

        case $PKG in
           kiss) rm -rf "$DEST/usr/bin" ;;

           *)
               rm -rf "$DEST/usr/share/doc"
               rm -rf "$DEST/usr/share/gettext"
               rm -rf "$DEST/usr/share/man"
               rm -rf "$DEST/usr/share/locale"
               rm -rf "$DEST/usr/share/polkit-1"
               rm -rf "$DEST/usr/share/info"
               rm -rf "$DEST/usr/share/gtk-doc"
               rm -rf "$DEST/usr/share/zsh"
               rm  -f "$DEST/usr/lib/charset.alias"
           ;;
        esac
    ;;
esac
