#!/bin/sh -e

[ "$1" ] || exit 1

read -r pkg <<EOF
    $(kiss s "$1")
EOF

[ -f "$pkg/sources" ] || exit 1

cache_dir=${XDG_CACHE_HOME:-$HOME/.cache}/kiss/sources/$1
mkdir -p "$cache_dir"
cd "$cache_dir"

while read -r src _ || [ "$src" ]; do
    case $src in
        https://*|http://*)
            aria2c -c "$src"
        ;;
    esac
done < "$pkg/sources"
