#!/bin/sh
# shellcheck disable=2016
#
# kiss-lint - regex based linter for shell nitpicks.

e() {
    printf '\033[34;1m%s\033[m [L%s] \033[31;1m=>\033[m %s\n' \
           "${file%/*}" "$n" "$1"

    [ "$2" ] && printf '\n   - %s\n\n' "$line"

    :> err
}

x() {
    [ "$(echo "$line" | sed -E "s|$2||")" = "$line" ] || e "$@"
}

find community -name build -or -name post-install |
    while read -r file; do
        n=0

        [ -x "$file" ] || e 'Build file not executable'

        while read -r line; do
            n=$((n+1))

            x 'Braces on bare variable: [${var} -> $var]' \
              '\$\{[a-zA-Z0-9_]*\}[^a-zA-Z0-9_]'

            x 'Shebang is missing -e: [#!/bin/sh -> #!/bin/sh -e]' \
              '^#!/bin/sh$'

            x 'Configure flags should be one per line.' \
              '\./configure [^\]*$'

            x 'Meson flags should be one per line.' \
              'meson [^\]*$'
        done < "$file"
    done

if [ -f err ]; then
    rm -f err
    exit 1
fi
