#!/usr/bin/env bash
#
# lnchr - dmenu replacement.

pal -r

while IFS= read -srn 1 -p $'\r\e[K'"launch ➜ $input"; do
    case $REPLY in
        $'\177')
            input=${input%?}
            unset c comp
        ;;

        $'\t')
            [[ -z ${comp[0]} ]] &&
                mapfile -t comp < <(compgen -c "$input")

            # On each tab press, cycle through the completion list.
            [[ -n ${comp[c]} ]] && {
                ((c=c >= ${#comp[@]}-1 ? 0 : ++c))
                input=${comp[c]}
            }
        ;;

        ""|$'\e')
            [[ -z $REPLY ]] &&
                sh -c "$input"

            exit
        ;;

        *)
            input+=$REPLY
            unset c comp
        ;;
    esac
done
