#!/bin/sh
#
# Read logs from #kisslinux irc channel.

curl "https://freenode.logbot.info/kisslinux/$(date +%Y%m%d)/raw" |

while read -r _ n m; do
    n=${n%>}
    n=${n#<}

    printf '%s %s\n' "$n" "$m"
done
