#!/usr/bin/env bash
#
# men - dmenu replacement.

enable -f /usr/lib/bash/sleep sleep
pal -r

while IFS= read -srn 1 -p $'\r\e[K'"run ➜ $input"; do
    case $REPLY in
        $'\177')
            input=${input%?}
            unset c comp
        ;;

        $'\t')
            [[ -z ${comp[0]} ]] &&
                mapfile -t comp < <(compgen -c "$input")

            [[ -n ${comp[c]} ]] && {
                ((c=c >= ${#comp[@]}-1 ? 0 : ++c))
                input=${comp[c]}
            }
        ;;

        $'\e')
            exit
        ;;

        "")
            xdotool getactivewindow windowminimize
            setsid "$input" &>/dev/null &
            sleep 2
            break
        ;;

        *)
            input+=$REPLY
            unset c comp
        ;;
    esac
done
