#!/bin/sh -e

dir=$PWD/root.x86_64
mount --bind "$dir" "$dir"
cd "$dir"
cp -f /etc/resolv.conf etc
mount --make-rslave --rbind /sys sys
mount --make-rslave --rbind /dev dev
mount --make-rslave --rbind /run run
mount --make-rslave --rbind /proc proc 
chroot "$dir" /bin/bash
