#!/usr/bin/env bash
# Download latest versions of mpv user-shaders and user-scripts.
#
# Created by Dylan Araps
#
# Dependencies: bash, wget


# User scripts/shaders to download

shaders=(
    "https://gist.githubusercontent.com/igv/a015fc885d5c22e6891820ad89555637/raw/CrossBilateral.glsl"
    "https://gist.githubusercontent.com/igv/2364ffa6e81540f29cb7ab4c9bc05b6b/raw/SSimSuperRes.glsl"
    "https://gist.githubusercontent.com/igv/8a77e4eb8276753b54bb94c1c50c317e/raw/adaptive-sharpen.glsl"
)

scripts=(
    "https://raw.githubusercontent.com/mpv-player/mpv/master/TOOLS/lua/autoload.lua"
    "https://raw.githubusercontent.com/Argon-/mpv-stats/master/stats.lua"
)


# Download the files


shader_dir="$HOME/.config/mpv/shaders"
script_dir="$HOME/.config/mpv/scripts"

# Create the directories if they don't exist.
mkdir -p "$script_dir"
mkdir -p "$shader_dir"

# Download the shaders
cd "$shader_dir" || exit
for shader in "${shaders[@]}"; do
    wget -O "${shader##*/}" "$shader"
done

# Download the scripts
cd "$script_dir" || exit
for script in "${scripts[@]}"; do
    wget -O "${script##*/}" "$script"
done
