#!/usr/bin/env bash
# vim: fdm=marker:noai:ts=4:sw=4
#
# Openbox menu
# Use the right click menu as a start button.
#
# Created by Dylan Araps

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

open () {
    # Save current mouse position
    mouse_pos="$(xdotool getmouselocation)"
    mouse_pos=${mouse_pos// screen*}
    mouse_pos=${mouse_pos//x:}
    mouse_pos=${mouse_pos//y:}

    # Get bar height
    height=$((${mon_height:-1080} * ${bar_percent:-3} / 100))

    # Move the mouse
    xdotool mousemove ${mon_width:-1920} $((${mon_height:-1080} - height))
    xdotool click 3
    xdotool mousemove $mouse_pos
}

install () {
cat <<EOF
[Desktop Entry]
Name=Openbox Menu
Exec=ob-menu --open
Icon=$HOME/dotfiles/themes/yellow/hamburger.png
Terminal=false
Type=Application
Categories=System;
EOF
}

# Args
case "$1" in
    --open) open ;;
    --install)
        mkdir -p "$HOME/.local/share/applications" 2>/dev/null
        install > "$HOME/.local/share/applications/ob-menu.desktop"
    ;;
esac
