#!/usr/bin/env bash
#
# Open files in applications by mime_type.
[[ -z $1 || ! -e $1 ]] &&
    exit 1

X() {
    # Run a GUI program without blocking the shell.
    nohup "$@" &>/dev/null & disown
}

mime_type="$(file -biL "$1")"

case "$mime_type" in
    text/*|*/xml|application/pgp*)
        "${VISUAL:-${EDITOR:-vi}}" "$1"
    ;;

    image/*)
        X qiv -tBl "$1"
    ;;

    video/*)
        X mpv "$1"
    ;;

    audio/*)
        X mpv "$1"
    ;;

    application/pdf*)
        X "${BROWSER:-firefox}" "$1"
    ;;

    *opendocument*|*openxmlformats*)
        X libreoffice "$1"
    ;;

    *)
        printf '%s\n' "warn: No program defined for $mime_type"
    ;;
esac
