#!/usr/bin/env bash
#
# Open files in applications by mime_type.

[[ -z $1 || ! -e $1 ]] &&
    exit 1

mime_type="$(file -biL "$1")"

case "$mime_type" in
    image/*|audio/*|video/*|*HEIC*)
        mpv "$1"
    ;;

    application/pdf*)
        "${BROWSER:-chromium}" "$1"
    ;;

    *opendocument*|*openxmlformats*)
        libreoffice "$1"
    ;;

    *)
        printf '%s\n' "warn: No program defined for $mime_type"
    ;;
esac
