#!/usr/bin/env bash
#
# Show file perms in pure bash.

file="${1:-${HOME}/dotfiles}"

[[ -r $file ]] && r="r"
[[ -w $file ]] && w="w"
[[ -x $file ]] && x="x"

printf '%s\n' "$file: ${r:--}${w:--}${x--}"
