#!/bin/sh
(
    read -r _ _ k _ < /proc/version
    IFS=. read -r s _ < /proc/uptime
    d=$((s/60/60/24))
    h=$((s/60/60%24))
    m=$((s/60%60))

    [ "$d" != 0 ] && u="$u ${d}d"
    [ "$h" != 0 ] && u="$u ${h}h"
    [ "$m" != 0 ] && u="$u ${m}m"

    read -r name < /sys/devices/virtual/dmi/id/product_name
    read -r vers < /sys/devices/virtual/dmi/id/product_version
    . /etc/os-release

    while IFS=: read -r a b; do
        b=${b%kB}
        case $a in
            MemT*) _=$((z+=b));_=$((y=b)) ;;
            Shmem) _=$((z+=b)) ;;
            MemF*|Buf*|Cac*|SR*) _=$((z-=b))
        esac
    done </proc/meminfo
    _=$((z/=1024))
    _=$((y/=1024))

    printf '%b\n' "
\033[34;1m    ___      \033[33m${USER:-$(whoami)}\033[m@\033[33;1m${HOSTNAME:-$(hostname)}\033[m
\033[34;1m   (\033[37m.· \033[34m|     \033[31mos\033[m:     ${PRETTY_NAME:-Linux}
\033[34;1m   (\033[35m<> \033[34m|     \033[31mshell\033[m:  ${SHELL:-/bin/sh}
\033[34;1m  / \033[37m__  \033[34m\\    \033[31mmodel\033[m:  $name $vers
\033[34;1m ( \033[37m/  \\ \033[34m/|   \033[31muptime\033[m:${u:-0m}
\033[35;1m_\033[34m/\\ \033[37m__)\033[34m/\033[35m_\033[34m)   \033[31mmemory\033[m: ${z:-?}MB / ${y:-?}MB
\033[35;1m\/\033[34m-____\033[35m\/    \033[31mkernel\033[m: ${k:-linux}
") 2>/dev/null


