#!/bin/sh
(
    read -r _ _ k _ < /proc/version
    IFS=. read -r s _ < /proc/uptime
    d=$((s/60/60/24))
    h=$((s/60/60%24))
    m=$((s/60%60))

    [ "$d" != 0 ] && u="$u ${d}d"
    [ "$h" != 0 ] && u="$u ${h}h"
    [ "$m" != 0 ] && u="$u ${m}m"

    read -r name < /sys/devices/virtual/dmi/id/product_name
    read -r vers < /sys/devices/virtual/dmi/id/product_version
    . /etc/os-release

    while IFS=: read -r a b; do
        b=${b%kB}
        case $a in
            MemT*) _=$((z+=b));_=$((y=b)) ;;
            Shmem) _=$((z+=b)) ;;
            MemF*|Buf*|Cac*|SR*) _=$((z-=b))
        esac
    done </proc/meminfo
    _=$((z/=1024))
    _=$((y/=1024))

    echo "
    ___     ${USER:-$(whoami)}@$(hostname)
   (.· |    os:     ${PRETTY_NAME:-Linux}
   (<> |    shell:  ${SHELL:-/bin/sh}
  / __  \   model:  $name $vers
 ( /  \ /|  uptime:${u:-?}
_/\ __)/_)  memory: ${z:-?}MB / ${y:-?}MB
\/-____\/   kernel: ${k:-?}
") 2>/dev/null
