#!/usr/bin/env bash
#
# Get the previous month.

months=(
    January
    February
    March
    April
    May
    June
    July
    August
    September
    October
    November
    December
)

# Get the current month index.
printf -v month '%(%m)T'

# Use the current month as a key in the list above.
prev_month=${months[month-2]}

# Print it (for the example).
printf '%s\n' "$prev_month"
