#!/usr/bin/env bash
#
# Simple CLI for qemu.

main() {
    [[ -f $1 ]] || { printf '%s\n' "iso file doesn't exist."; exit 1; }

    read -rp "creating disk. enter size [4G]: " size
    read -rp "creating disk. enter name [disk-iso-random]: " name

    qemu-img create -f raw "${name:=disk-${1##*/}-${size}}" "${size:=4G}"
    qemu-system-x86_64 -m 1024 -cdrom "$1" -boot "order=d" -drive "file=$name,format=raw"
}

main "$@"
