#!/bin/sh

# -f alsa -ac 2 -i hw:0 \
ffmpeg \
    -video_size 1920x1080 \
    -framerate 60 \
    -f x11grab \
    -i :0.0 \
    -c:v libx264 \
    -crf 0 \
    -preset ultrafast \
    -y \
    output.mkv

# ffmpeg \
#     -y \
#     -vaapi_device /dev/dri/renderD128 \
#     -f x11grab \
#     -video_size 1920x1080 \
#     -i :0 \
#     -vf 'hwupload,scale_vaapi=format=nv12' \
#     -c:v h264_vaapi \
#     -qp 24  \
#     output.mp4
