#!/bin/sh
ffmpeg \
    -hwaccel vaapi \
    -hwaccel_output_format vaapi \
    -vaapi_device /dev/dri/renderD128 \
    -video_size 3200x1800 \
    -framerate 60 \
    -f x11grab \
    -i ':0' \
    -vf 'format=nv12|vaapi,hwupload,scale_vaapi=w=1920:h=1080' \
    -c:v h264_vaapi  \
    -qp 19 \
    -bf 2 \
    -threads 2 \
    -y \
    -f matroska \
    -vcodec h264_vaapi \
    "$1".mkv
