#!/usr/bin/env bash
#
# List all dependencies of a package
# and its dependencies.

mapfile -t deps < <(xbps-query -x "$1")

for dep in "${deps[@]}"; do
    echo "----------------------------"
    echo "${dep^^}"
    echo "----------------------------"

    xbps-query -x "$dep"
done
