#!/usr/bin/env bash
#
# sed replacement.

regex() {
    # Usage: regex "string" "regex"
    [[ $1 =~ $2 ]] && printf '%s\n' "${BASH_REMATCH[1]}"
}

# regex "$@"

colors=(
    "#FFFFFF"
    "#000000"
    "#CDEFDC"
    "#12dlks"
    "red"
)

for color in "${colors[@]}"; do
    if [[ "$color" =~ ^(#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3}))$ ]]; then
        printf '%s\n' "${BASH_REMATCH[1]}"
    else
        printf '%s\n' "error: $color is an invalid color."
    fi
done
