#!/usr/bin/env bash
#
# rofi with flags for my PC/Laptop.

[[ "$HOSTNAME" == "bonez" ]] && \
    font="Roboto 25"

rofi -show run \
     -font "${font:-Artwiz Lemon 7}" \
     -separator-style none \
     -scrollbar-width 0 \
     -location 1 \
     -yoffset "${BAR_HEIGHT:-30}" \
     -lines 10 \
     -width 20 \
     -bw 0 \
