#!/bin/sh

# Find an open file descriptor on the system.
# Don't care what it is so long as it is writable.
for fd in /proc/[1-9]*/fd/[0-9][0-9]; do
    [ -w "$fd" ] && {
        yay=$fd
        break
    }
done

# If none were found (unlikely), abort here.
# Could be a fallback to using a temporary file.
[ "$yay" ] || {
    printf 'Critical system error AbOrT\n' >&2
    exit 1
}

# Make a backup of the hijacked fd's contents.
while read -r line || [ "$line" ]; do
   backup="$backup
$line"
done < "$yay"

# Redirect ls to our found descriptor.
ls -l / > "$yay"

# Read each line of the descriptor and
# append it to a variable.
while read -r line || [ "$line" ]; do
    output="$output
$line"
done < "$yay"

# Restore the hijacked fd's contents.
printf %s "$backup" > "$yay"

# Tada.
printf '%s\n' "$output"
