#!/usr/bin/env bash
#
# Take a screenshot and display a notification.
#
# Created by Dylan Araps.
#
# Depends on: imagemagick, libnotify (patched with id support)
scr_dir="${HOME}/Pictures/Screenshots"

printf -v date "%(%F)T" "-1"
printf -v time "%(%I-%M-%S)T" "-1"

mkdir -p "${scr_dir}/${date}"
scr="${scr_dir}/${date}/${date}-${time}"

# sleep 2
# notify-send " Saved screenshot as ${scr/*\/}"
import -window root "$scr".png &
import -window root "$scr".jpg &
