#!/bin/sh
#
# Take a screenshot.

scr_dir=~/pictures/screenshots

date=$(date +%F)
time=$(date +%I-%M-%S)
file=$scr_dir/$date/$date-$time.jpg

mkdir -p "$scr_dir/$date"

ffmpeg -y \
    -f x11grab \
    -video_size 1920x1080 \
    -i :0.0 \
    -vframes 1 \
    "$file" 2>/dev/null

ffmpeg -y \
    -f x11grab \
    -video_size 1920x1080 \
    -i :0.0 \
    -vframes 1 \
    "${file%%.jpg}.png" 2>/dev/null

cp -f "$file" "$scr_dir/current.jpg"
cp -f "${file%%.jpg}.png" "$scr_dir/current.png"
