#!/bin/sh

trap 'stty icanon echo; kill 0' INT

key() {
    key=$(dd ibs=1 count=1 2>/dev/null)

    case $key in
        # Down
        j|B) cur=$((cur + 1 > tot - 1 ? tot - 1 : cur + 1)) ;;

        # Up
        k|A) cur=$((cur - 1 < 0 ? 0 : cur - 1)) ;;

        # Special
        '') key ;;

        # Enter
        '')
            shift "$cur"
            printf '[2J[H%s\n' "$1"
            stty icanon echo
            exit
        ;;
    esac
}

pri() {
    i=0

    printf '\e[2J\e[H'

    for item; do
        if [ "$i" = "${cur:-0}" ]; then
            printf '[7m%s[m\n' "$item"
        else
            printf '%s\n' "$item"
        fi

        i=$((i+1))
    done
}

main() {
    while read -r line || [ "$line" ]; do
        set -- "$@" "$line"
    done

    tot=$#

    exec </dev/tty >/dev/tty || exit

    stty -icanon -echo

    while :; do
        pri "$@"
        key "$@"
    done
}

main
