#!/usr/bin/env bash
#
# Convert string to octal

str2ascii() {
    string="$1"

    for ((i=0;i<${#string};i++)); {
        LC_CTYPE=C printf '%d' "'${string:i}"
    }

    printf '\n'
}

time str2ascii "hello, world!"
