#!/usr/bin/env bash
#
# tek - Upload image to teknik.io.

file=${1:-$(< ~/.cache/scrot)}

[[ -f $file ]] ||
    exit 1

: https://api.teknik.io/v1/Upload
: "$(curl -sF file="@${file};type=image/${file: -3}" "$_")"
: "${_##*fileName\":\"}"

printf '%s\n' "https://u.teknik.io/${_%%\"*}"
