#!/usr/bin/env bash
#
# Test time between tput vs sequence.

    raw() {
        printf '%s\n' "raw:"
        for i in {1..15}; do printf '\e[38;5;5m'; done
    }

    ext_no_subshell() {
        for i in {1..15}; do tput setaf 5; done
    }

    ext_subshell() {
        for i in {1..15}; do echo -n "$(tput setaf 5)"; done
    }

    printf '\n%s\n' "raw:"
    time raw >/dev/null >/dev/null

    printf '\n%s\n' "ext:"
    time ext_no_subshell >/dev/null

    printf '\n%s\n' "ext (subshell):"
    time ext_subshell >/dev/null

