#!/bin/sh

convert \
    -size 2000x300 \
    xc:none \
    -font Baskerville \
    -pointsize 250 \
    -gravity east \
    -draw "fill white  text 0,0  'KISS LINUX'" \
    ~/txt.png

composite \
    -gravity southeast \
    -geometry +100+50 \
    ~/txt.png  \
    "$1" \
    ~/new.jpg
