#!/usr/bin/env bash
#
# Generate a UUID.

k=89ab
for ((i=0;j=RANDOM%256,i<16;++i)); do
    case $i in
        6)       printf '4%x'   "$((j%16))" ;;
        8)       printf '%c%x'  "${k:RANDOM%${#k}:1}" "$((j%16))" ;;
        3|5|7|9) printf '%02x-' "$j" ;;
        *)       printf '%02x'  "$j" ;;
    esac
done
printf '\n'
