#!/usr/bin/env bash

# Assign to a variable named after the
# value stored in '$var'.
var="test"
read -rp "input text: " "$var"

# Access the variable indirectly.
printf '%s\n' "set var \$$var to '${!var}'"

# Access the variable directly.
printf '%s\n' "set var \$$var to '$test'"
