#!/usr/bin/env bash
#
# Change pulseaudio volume and send a notification.
#
# Created by Dylan Araps.
#
# Depends on: amixer, libnotify (patched with id support)
case "$1" in
    "up")   amixer -q sset Master 5%+ ;;
    "down") amixer -q sset Master 5%- ;;
    "mute") amixer -q sset Master toggle ;;
    *) printf "%s\n" "Usage: ./vol up, ./vol down"; exit ;;
esac

vol="$(amixer -c 1 -M -D pulse get Master | grep -o -E "[[:digit:]]+%")"

# The '-r' flag is from a patched version of 'libnotify'.
# '-r' lets you replace notifications using the same id.
notify-send -t 1 -r 112 "Volume: ${vol/$'\n'*}"

