#!/usr/bin/env bash
#
# web

chromium \
    --process-per-site \
    --disable-background-networking \
    --disable-breakpad \
    --disable-domain-reliability \
    --disable-gpu-sandbox \
    --disable-sync \
    --in-process-gpu \
    --no-pings \
    --process-per-site \
    --single-process
