#!/usr/bin/env bash
#
# batmon

# Change this to match your distro's location.
enable -f /usr/lib/bash/sleep sleep

# Change this is yours differs
bat_file=/sys/class/power_supply/BAT1/capacity

[[ -f $bat_file ]] || {
    printf '%s\n' "error: Battery file not found."
    exit 1
}

for ((;;)) {
    [[ $(< "$bat_file") -le 10 ]] && {
        : "do thing"
    }

    sleep 1
}
