#!/usr/bin/env bash
#
# bar - Dylan Araps

enable -f /usr/lib/bash/sleep sleep

for ((;;)) {
    printf '%%{c}%(%I:%M)T\n' -1
    sleep 60
} | lemonbar -d -b \
             -n bar_clo \
             -B "#FFFFFF" \
             -F "#000000" \
             -f "Roboto Mono:size=16" \
             -f "Font Awesome:size=18" \
             -g "300x120+2450+50"
