#!/bin/bash
trap 'printf \\e[?25h' EXIT
# IFS='[;' read -d R -rsp $'\e7\e[9999;9999H\e[6n\e8' _ h w
shopt -s checkwinsize; (:)
:(){ printf -v s '%s%*s' "$s" "$[(${#2}+w)/2]" "$2";}
mapfile -C : -c1 f < "$1" || exit 1
read -srt 10 -p $'\e[2J\e[?25l\e['"$[(h-${#f[@]})/2]H$s"

# 1. trap 'exit' to unhide cursor.
# 2. get terminal size by moving cursor to bottom right corner.
# 3. define a function to use as a callback with mapfile.
# 4. read the file line by line and run '3' on each line.
# 5. display the file data centered and wait 10 seconds.

