#!/bin/bash -i
#
# Detect cursor position and add padding.
export LC_ALL=C
export LANG=C

printf "%b" "\\e[s\\e[6n"
read -rsd"["
read -rsd";" pos
read -rsd"R"

printf "%b" "\\e[1000B\\e[6n\\e[u"
read -rsd"["
read -rsd";" pos2
read -rsd"R"

((pos == pos2)) && printf "\\n\\n\\n"
