#!/usr/bin/env bash
#
# Find the full path to a file in pure bash.

enable -f /usr/lib/bash/realpath realpath

cd "${1%/*}" &>/dev/null ||:

: "$PWD/${1##*/}"

if [[ -L $_ ]]; then
    realpath "$_"

elif [[ -e $_ ]]; then
    printf '%s\n' "$_"
fi
