#!/usr/bin/env bash
#
# heif2jpg

shopt -s globstar

for img in ~/PHOTOS/**/*.HEIC; do
    name=${img##*/}

    [[ -f ~/PHOTOS/out/${name/HEIC/jpg} ]] ||
        /home/black/build/libheif/examples/heif-convert \
            "$img" ~/PHOTOS/out/"${name/HEIC/jpg}"
done
