#!/usr/bin/env bash
#
# kernel_build

clean() {
    sudo xbps-remove -yR "${build_deps[@]}" &>/dev/null
}

build_deps=(
    base-devel
    ncurses-devel
    elfutils-devel
    libressl-devel
)
clean

