#!/usr/bin/env bash
dirs=(
    "${HOME}/music/*.mp3"
    "${HOME}/wallpapers/*.png"
)

mkdir -p "${dirs[@]%/*}" || exit 1
cd "${HOME}/Downloads" || exit 1

for dir in "${dirs[@]}"; do
    mapfile -t files < <(compgen -G "./${dir#*/}")
    mv -i "${files[@]}" "${dir%/*}" 2>/dev/null
done
