#!/bin/sh

find /sys -name modalias -type f |
    while read -r line; do
        IFS='
' read -r alias < "$line"
        modprobe -b -a "$alias" 2>/dev/null
    done

for file in /sys/class/net/*/uevent; do
    printf '%s\n' add > "$file"
done 2>/dev/null

for file in /sys/bus/usb/devices/*; do
    case ${file##*/} in
        [0-9]*-[0-9]*)
            printf '%s\n' add > "$file/uevent"
        ;;
    esac
done
