#!/usr/bin/env bash
#
# nrt - testing namerefs

random_array_element() {
    arr=("$@")
    printf '%s\n' "normal: ${arr[RANDOM % $#]}"
}

random_array_element_no_arr() {
    printf '%s\n' "no arr: ${@:$((RANDOM % $#)):1}"
}

random_array_element_nameref() {
    declare -n array="$1"
    printf '%s\n' "nameref: ${array[RANDOM%${#array[@]}]}"
}

nums=({1..10000})

time random_array_element_nameref "nums"
time random_array_element_no_arr "${nums[@]}"
time random_array_element "${nums[@]}"
