#!/usr/bin/env bash
#
# Pure bash 'cal'.

[[ $1 ]] && day=$1   || printf -v day   '%(%e)T' -1
[[ $2 ]] && month=$2 || printf -v month '%(%m)T' -1
[[ $3 ]] && year=$3  || printf -v year  '%(%Y)T' -1

months=(0
   0-January   3-February 3-March    6-April
   1-May       4-June     6-July     2-August
   5-September 0-October  3-November 5-December
)

case ${year::2} in
    16|20|24) century=6 ;;
    17|21|25) century=4 ;;
    18|22)    century=2
esac

((leap      = year%4?year%100?0:year%400?1:1:1))
((year_code = (${year:2}+(${year:2}/4))%7))
((start     = (year_code+${months[month]::1}+century+leap+1)%7%7))

[[ ${month#0} == [469] ]] && ((days=30))
[[ ${month#0} == 11 ]]    && ((days=30))
[[ ${month#0} == 2 ]]     && ((days=leap?29:28))

printf '%10s %s\nSu Mo Tu We Th Fr Sa\n' "${months[month]:2}" "$year"

for ((;i++<${days:-31};)) {
    ((i==1))   && printf "%$((start*3))s"
    ((i==day)) && printf '\e[7m'

    printf '%2s\e[m ' "$i"

    ((i==days||(i+start)%7)) || printf '\n'
}

printf '\n\n'
