#!/bin/bash
mapfile -tn99 r </d*/ur*
r=("${r[@]//[^[:print:]]}")
for((;;)){
    for ((i=0;i++<10;)){
        printf %b \\e[32m"${r[RANDOM%${#r[@]}]:0:1}"\ \\e[m\\n
        read -d "" -t 0.05 -N 999
    }
}
