#!/usr/bin/env bash
#
# Manipulate string casing in pure bash.

# Lowercase
for ((i=0;i<${#1};i++)); {
    [[ ${1:i:1} == [A-Z] ]] && {
        printf -v dec %d "'${1:i:1}"
        printf -v oct %o "$dec"
        printf '%b' "\\$((oct+40))"
        continue
    }
    printf '%s' "${1:i:1}"
}
printf '\n'

# Uppercase
for ((i=0;i<${#1};i++)); {
    [[ ${1:i:1} == [a-z] ]] && {
        printf -v dec %d "'${1:i:1}"
        printf -v oct %o "$dec"
        printf '%b' "\\$((oct-40))"
        continue
    }
    printf '%s' "${1:i:1}"
}
printf '\n'
