#!/usr/bin/env bash
#
# Mouse tracking.

key() {
    case "${1: -1}" in
        # Mouse click.
        M)
            IFS=\; read -rsa pos <<< "${1/'^['}"
            printf '\e[%sH' "${pos[2]/M};${pos[1]}"
        ;;
    esac
}

main() {
    # Clear screen.
    printf '\e[2J\e[H'

    # Enable mouse tracking.
    printf '\e[?1000h\e[?1006h'

    # Disable mouse tracking on exit.
    trap 'printf \\e[2J\\e[H\\e[?1000l\\e[m' EXIT

    # Read loop
    for ((;;)); {
        read -d "" -t 0.010 -rs key
        key "$key"
    }
}

main
