#!/usr/bin/env bash
#
# upt
if [[ -r /proc/uptime ]]; then
    seconds="$(< /proc/uptime)"
    seconds="${seconds/.*}"
else
    boot="$(date -d"$(uptime -s)" +%s)"
    now="$(date +%s)"
    seconds="$((now - boot))"
fi

echo "uptime: $seconds"
