#!/usr/bin/env bash
#
# url_encode

for ((i=0;i<${#1};i++)) {
    s=${1:i:1}

    if [[ $s == [a-zA-Z0-9.~_-] ]]; then
        printf %s "$s"

    else
        printf '%%%02X' "'$s"
    fi
}

printf '\n'
